### ISSUE TITLE
Probability of pairing greater than 1

### ISSUE THREAD

**Issue by domen13** [eternagame/EternaFold#2]
### Expected Behavior

Probability of pairing $p_i$, calculated as a sum of all pairing probabilities $p_{ij}$, should not exceed unity, $p_i = \sum_j p_{ij} \leq 1$.

### Current Behavior

For longer sequences, probability of pairing for certain nucleotides exceeds 1, the difference being significantly greater than one would expect from numerical instabilities.

### Reproduction Steps

Fold the following MS2 sequence ([MS2_short.txt](https://github.com/eternagame/EternaFold/files/12524956/MS2_short.txt)) with default parameters:
````bash
./src/contrafold predict MS2_short.txt --params parameters/EternaFoldParams.v1 --posteriors 0.00001 MS2_bps.txt
````

Looking at the obtained pair probability matrix ([MS2_bps.txt](https://github.com/eternagame/EternaFold/files/12524982/MS2_bps.txt)), one observes the following two lines:

````
571 C 613:0.00438902 616:0.996947
572 C 612:0.00449777 615:0.996294
````
The total pairing probability for nucleotides 571 and 572 therefore exceeds 1: $p_{571} = 1.00134$, $p_{572}= 1.000792$.

**Comment by tkaragianes** [comment]
Great, thanks for this issue! We're looking into it, and we'll let you know about a fix soon. This might to be related to an issue that Contrafold had and has since fixed, so hopefully simple to resolve.

Tagging @rhiju @HWaymentSteele.

**Comment by rhiju** [comment]
@domen13 Thanks again for bringing this to our attention. 

My lab hasn't been able to attend to this, but we can provide some quick advice.

Some time ago, @HWaymentSteele and I had noticed a similar bug in the [LinearPartition](https://github.com/LinearFold/LinearPartition) implementation of Contrafold. The code's authors eventually fixed the issue by using double instead of float and `exp()` instead of `FastExp()`.

Here's a suggestion -- have you tried to run EternaFold with LinearPartition (following [these instructions](https://github.com/eternagame/EternaFold/blob/master/README_LinearFold-E_patch.md)?  If so, do you still see probability of pairing greater than 1?   

If LinearPartition-E is OK, then you could potentially just use it for your tests. If you have the interest, it would be helpful then to also patch up the (non-linearized) ContraFold code that we have in the EternaFold repository -- and that could be a simple matter of updating float to double. Could you help us explore that with your test cases?

**Comment by domen13** [comment]
@rhiju, thank you a lot for your response and suggestion!

I have now tested my sequence (along with a set of random sequences) on EternaFold and LinearPartition (either with ContraFold, ViennaRNA or EternaFold parameters), and it seems that your suggestion works! Neither LinearPartition (ContraFold) nor LinearPartition (EternaFold) give corrupted probabilities. You can read a more detailed report [here](https://github.com/domen13/LinearPartition/tree/eternafold_patch/tests).

Then, I changed `<float>` to `<double>` in [`Contrafold.cpp:121`](https://github.com/eternagame/EternaFold/blob/f77216d82595040f64412b3920bdf4cb32f4a8a6/src/Contrafold.cpp#L121C27-L121C32), and it looks like this solves the issue for EternaFold.

I have made a [PR]() to add `USE_DOUBLE_IN_PREDICT` in the configuration file.

**Comment by AMA-cs** [comment]
Hi, I know this issue is closed, but I have a question about this issue.

I see the new update (Contrafold.cpp) to resolve this issue:
```
// precision for prediction 
#if USE_DOUBLE_IN_PREDICT
typedef double pf_type;
#else
typedef float pf_type;
#endif
```
However, in the Config.hpp file, where the USE_DOUBLE_IN_PREDICT is defined, I see this line:
```
// use double precision for prediction 
#define USE_DOUBLE_IN_PREDICT                      0
```
doesn't this mean the float will be used since USE_DOUBLE_IN_PREDICT is 0?

Thank you

**Comment by domen13** [comment]
@AMA-cs, yes, you are correct. My proposed update was made in a way that it doesn't change the current (default) behavior, since this would lead to slightly different predictions and (I think) a slightly worse time performance. If you want to use double precision, you have to turn it on yourself in `Config.hpp`.

**Comment by AMA-cs** [comment]
@domen13  Thank you so much for your quick response. 

I don't mind the time performance as long as I get more accurate or reliable base-pairing probability prediction (probabilities sum to 1 for each nt)


> would lead to slightly different predictions


You mean because they now sum to 1? or it will affect the prediction in other way?

**Comment by domen13** [comment]
@AMA-cs, yes, I meant the slight differences in pairing probabilities due to higher precision. You can see an example of this in [my report](https://github.com/domen13/LinearPartition/tree/eternafold_patch/tests#pairing-probability-matrix-comparison-for-ms2) (histogram of $\Delta p_{ij}$ for EternaFold (double)). I don't think there should be any other side-effects, though ...

**Comment by AMA-cs** [comment]
@domen13 Do you know if this issue present in repo contrafold-se? 
https://github.com/csfoo/contrafold-se

Do I need to convert the float to double in this repo too?

**Comment by domen13** [comment]
@AMA-cs, yes, I observe the same issue. You should change `<float>` to `<double>` before compiling in https://github.com/csfoo/contrafold-se/blob/64f01d52f8fcba2b88c0011d56360554b9a95012/src/Contrafold.cpp#L79
